Import('*')

env = env.Clone()

env.Append(CPPDEFINES = [
    'DEFAULT_DRIVER_DIR=\\"\\"'
])

env.Append(CPPPATH = [
    '#/include',
    '#/src/egl/main',
    '#/src/loader',
])

sources = [
    'egl_dri2.c',
]

if env['platform'] == 'haiku':
    sources.append('platform_haiku.cpp')
    env.Append(CPPDEFINES = [
        'HAVE_HAIKU_PLATFORM',
    ])

if env['x11']:
    sources.append('platform_x11.cpp')
    env.Append(CPPDEFINES = [
        'HAVE_X11_PLATFORM',
    ])
    env.Append([CPPPATH = [
#        'XCB_DRI2_CFLAGS',
    ])

egl_dri2 = env.ConvenienceLibrary(
    target = 'egl_dri2',
    source = sources,
)

Export('egl_dri2')
