#!/bin/sh

AVAIL_FUNCS="$(nm -D --format=bsd --defined-only ${1-.libs/libGLESv1_CM.so.1} | awk '{print $3}')"

# Platform specific, "optional", symbols.
PLAT_FUNCS="__bss_start
_edata
_end
_fini
_init
"

# Official ABI, taken from the public headers.
# (FIXME, none of these should be part of the ABI)
# GL_EXT_multi_draw_arrays
# GL_OES_EGL_image

# or in extensions that are part of the ES 1.1 extension pack.
# (see http://www.khronos.org/registry/gles/specs/1.1/opengles_spec_1_1_extension_pack.pdf)
REQ_FUNCS="glActiveTexture
glAlphaFunc
glAlphaFuncx
glBindBuffer
glBindTexture
glBlendFunc
glBufferData
glBufferSubData
glClear
glClearColor
glClearColorx
glClearDepthf
glClearDepthx
glClearStencil
glClientActiveTexture
glClipPlanef
glClipPlanex
glColor4f
glColor4ub
glColor4x
glColorMask
glColorPointer
glCompressedTexImage2D
glCompressedTexSubImage2D
glCopyTexImage2D
glCopyTexSubImage2D
glCullFace
glDeleteBuffers
glDeleteTextures
glDepthFunc
glDepthMask
glDepthRangef
glDepthRangex
glDisable
glDisableClientState
glDrawArrays
glDrawElements
glEGLImageTargetRenderbufferStorageOES
glEGLImageTargetTexture2DOES
glEnable
glEnableClientState
glFinish
glFlush
glFogf
glFogfv
glFogx
glFogxv
glFrontFace
glFrustumf
glFrustumx
glGenBuffers
glGenTextures
glGetBooleanv
glGetBufferParameteriv
glGetClipPlanef
glGetClipPlanex
glGetError
glGetFixedv
glGetFloatv
glGetIntegerv
glGetLightfv
glGetLightxv
glGetMaterialfv
glGetMaterialxv
glGetPointerv
glGetString
glGetTexEnvfv
glGetTexEnviv
glGetTexEnvxv
glGetTexParameterfv
glGetTexParameteriv
glGetTexParameterxv
glHint
glIsBuffer
glIsEnabled
glIsTexture
glLightf
glLightfv
glLightModelf
glLightModelfv
glLightModelx
glLightModelxv
glLightx
glLightxv
glLineWidth
glLineWidthx
glLoadIdentity
glLoadMatrixf
glLoadMatrixx
glLogicOp
glMaterialf
glMaterialfv
glMaterialx
glMaterialxv
glMatrixMode
glMultiDrawArraysEXT
glMultiDrawElementsEXT
glMultiTexCoord4f
glMultiTexCoord4x
glMultMatrixf
glMultMatrixx
glNormal3f
glNormal3x
glNormalPointer
glOrthof
glOrthox
glPixelStorei
glPointParameterf
glPointParameterfv
glPointParameterx
glPointParameterxv
glPointSize
glPointSizePointerOES
glPointSizex
glPolygonOffset
glPolygonOffsetx
glPopMatrix
glPushMatrix
glReadPixels
glRotatef
glRotatex
glSampleCoverage
glSampleCoveragex
glScalef
glScalex
glScissor
glShadeModel
glStencilFunc
glStencilMask
glStencilOp
glTexCoordPointer
glTexEnvf
glTexEnvfv
glTexEnvi
glTexEnviv
glTexEnvx
glTexEnvxv
glTexImage2D
glTexParameterf
glTexParameterfv
glTexParameteri
glTexParameteriv
glTexParameterx
glTexParameterxv
glTexSubImage2D
glTranslatef
glTranslatex
glVertexPointer
glViewport
"

NEW_ABI=$(echo "$AVAIL_FUNCS" | while read func
do
    echo "$REQ_FUNCS" | grep -q "^$func$" && continue
    echo "$PLAT_FUNCS" | grep -q "^$func$" && continue

    echo $func
done)

test ! -n "$NEW_ABI" || echo "New ABI detected - If intentional, update the test."; echo "$NEW_ABI"

REMOVED_ABI=$(echo "$REQ_FUNCS" | while read func
do
    echo "$AVAIL_FUNCS" | grep -q "^$func$" && continue

    echo $func
done)

test ! -n "$REMOVED_ABI" || echo "ABI break detected - Required symbol(s) no longer exported!"; echo "$REMOVED_ABI"
test ! -n "$NEW_ABI" || test ! -n "$REMOVED_ABI"
