#!/bin/sh

AVAIL_FUNCS="$(nm -D --format=bsd --defined-only ${1-.libs/libEGL.so} | awk '{print $3}')"

# Platform specific, "optional", symbols.
PLAT_FUNCS="__bss_start
_edata
_end
_fini
_init
"

# Official ABI, taken from the public headers.
# Note: wl_drm_interface should not be here, but that requires wayland-scanner fixes.
# Note: MesaGLInteropEGL* are internal symbols used for interoperability across
# different APIs. See mesa_glinterop.h for details.
REQ_FUNCS="eglBindAPI
eglBindTexImage
eglChooseConfig
eglCopyBuffers
eglCreateContext
eglCreatePbufferFromClientBuffer
eglCreatePbufferSurface
eglCreatePixmapSurface
eglCreateWindowSurface
eglDestroyContext
eglDestroySurface
eglGetConfigAttrib
eglGetConfigs
eglGetCurrentContext
eglGetCurrentDisplay
eglGetCurrentSurface
eglGetDisplay
eglGetError
eglGetProcAddress
eglInitialize
eglMakeCurrent
eglQueryAPI
eglQueryContext
eglQueryString
eglQuerySurface
eglReleaseTexImage
eglReleaseThread
eglSurfaceAttrib
eglSwapBuffers
eglSwapInterval
eglTerminate
eglWaitClient
eglWaitGL
eglWaitNative
MesaGLInteropEGLQueryDeviceInfo
MesaGLInteropEGLExportObject
wl_drm_interface
"

NEW_ABI=$(echo "$AVAIL_FUNCS" | while read func
do
    echo "$REQ_FUNCS" | grep -q "^$func$" && continue
    echo "$PLAT_FUNCS" | grep -q "^$func$" && continue

    echo $func
done)

test ! -n "$NEW_ABI" || echo "New ABI detected - If intentional, update the test."; echo "$NEW_ABI"

REMOVED_ABI=$(echo "$REQ_FUNCS" | while read func
do
    echo "$AVAIL_FUNCS" | grep -q "^$func$" && continue

    echo $func
done)

test ! -n "$REMOVED_ABI" || echo "ABI break detected - Required symbol(s) no longer exported!"; echo "$REMOVED_ABI"
test ! -n "$NEW_ABI" || test ! -n "$REMOVED_ABI"
